 <Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <RootNamespace>Core</RootNamespace>
	<RuntimeIdentifier>win-x64</RuntimeIdentifier>
	<Platforms>x64</Platforms>
    <WinUISDKReferences>false</WinUISDKReferences>
	<AppendRuntimeIdentifierToOutputPath>true</AppendRuntimeIdentifierToOutputPath>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="HotChocolate.Data.EntityFramework" Version="15.1.12" />
    <PackageReference Include="HotChocolate.Language" Version="15.1.14" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.0" />
    <PackageReference Include="System.Security.Cryptography.Xml" Version="9.0.15" />
  </ItemGroup>
  
</Project>