<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
	<RuntimeIdentifier>win-x64</RuntimeIdentifier>
	<Platforms>x64</Platforms>
	<SelfContained>true</SelfContained>
	<AppendRuntimeIdentifierToOutputPath>true</AppendRuntimeIdentifierToOutputPath>
	<ImplicitUsings>enable</ImplicitUsings>
	<Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.1.0" />
    <PackageReference Include="HotChocolate.AspNetCore" Version="15.1.12" />
    <PackageReference Include="HotChocolate.Data.EntityFramework" Version="15.1.12" />
    <PackageReference Include="HotChocolate.Language" Version="15.1.14" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Obfuscar" Version="2.2.50">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Core\Core.csproj" />
  </ItemGroup>

	<ItemGroup>
		<None Update="obfuscar_api.xml">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<CopyToPublishDirectory>Never</CopyToPublishDirectory>
		</None>
	</ItemGroup>

	<Target Name="ObfuscarTask" AfterTargets="Build" Condition="'$(Configuration)' == 'Release'">
		<MakeDir Directories="$(TargetDir)Obfuscated" />
		<Exec Command="&quot;$(Obfuscar)&quot; obfuscar_api.xml" WorkingDirectory="$(TargetDir)" />
	</Target>

</Project>
